name: Hola mundo

on: [push]

jobs:
  node-test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306

    steps:
      - name: Test mysql ls
        run: ls
