name: Hola mundo

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: ls
      run: |
        chmod +x script.sh
        ./script.sh

  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: LS
      run: ls -al